# This workflow will build and test a Go project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['stable'] # Test against the stable version of Go

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Run tests with coverage (optional)
      run: |
        go test -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out

    - name: Clean Go module cache
      run: |
        if [ -d ~/go/pkg/mod/ ]; then
          chmod -R u+w ~/go/pkg/mod/
          rm -rf ~/go/pkg/mod/
        else
          echo "Go module cache does not exist, skipping clean."
        fi

    - name: Debug Go module cache
      run: |
        if [ -d ~/go/pkg/mod/ ]; then
          ls -R ~/go/pkg/mod/
        else
          echo "Go module cache does not exist."
        fi

    - name: Clean workspace
      run: rm -rf ${{ github.workspace }}/*
