# This workflow will build and test a Go project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['stable'] # Test against multiple Go versions

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Install dependencies
      run: go mod tidy
    
    - name: Debug cache
      run: |
        if [ -d ~/go/pkg/mod/ ]; then
          ls -R ~/go/pkg/mod/
        else
          echo "Go module cache does not exist."
        fi
    
    - name: Modify permissions of Go module cache
      run: |
        if [ -d ~/go/pkg/mod/ ]; then
          chmod -R u+w ~/go/pkg/mod/
        else
          echo "Go module cache does not exist, skipping chmod."
        fi
    
    - name: Clean module cache
      run: |
        if [ -d ~/go/pkg/mod/ ]; then
          rm -rf ~/go/pkg/mod/
        else
          echo "Go module cache does not exist, skipping clean."
        fi
